name: Push to Replicate

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4

      - uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - run: cog push r8.im/tianyi/qwen-image-layered
